apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/postgres/persistent-volume.yaml
  - ../../base/postgres/deployment.yaml
  - ../../base/postgres/service.yaml
  - ../../base/backend/deployment.yaml
  - ../../base/backend/service.yaml

patchesStrategicMerge:
  - backend-env-patch.yaml
