version: '3.8'

services:
  backend:
    build:
      context: https://github.com/tu-usuario/citary-backend.git
      dockerfile: Dockerfile
    deploy:
      replicas: 3
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
    environment:
      - NODE_ENV=production
      - LOG_LEVEL=info
    # Remover el puerto expuesto directamente
    expose:
      - '3000'

  frontend:
    build:
      context: https://github.com/tu-usuario/citary-frontend.git
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://backend:3000
    deploy:
      replicas: 2
      resources:
        limits:
          memory: 256M
          cpus: '0.25'
        reservations:
          memory: 128M
          cpus: '0.1'
    expose:
      - '5173'

  # Nginx como reverse proxy y load balancer
  nginx:
    image: nginx:alpine
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - backend
    networks:
      - citary-network
    deploy:
      replicas: 1
      resources:
        limits:
          memory: 128M
          cpus: '0.1'
