version: '3.8'

services:
  backend:
    volumes:
      - ../../citary-backend:/app_backend
      - /app_backend/node_modules
      - backend_logs:/app_backend/logs
    environment:
      - DEBUG=true
      - LOG_LEVEL=debug
      - NODE_ENV=development
    # Hot reload habilitado
    command: npm run dev

  frontend:
    volumes:
      - ../../citary-frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    # Hot reload habilitado
    command: npm run dev -- --host 0.0.0.0

  database:
    ports:
      - '5432:5432'
    # Opcional: Agregar volumen para scripts SQL en desarrollo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ../../citary-database:/docker-entrypoint-initdb.d/
