apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: citary
spec:
  type: ClusterIP
  ports:
  - port: 5173
    targetPort: 5173
    protocol: TCP
    name: http
  selector:
    app: frontend